### PR TITLE
fixes #45, patching a parsing bug

### LINKED ISSUE #45: App not pulling data
No models available shown though models available through online

### PR DESCRIPTION
**Pull request by worthbak**
the fulfillment API moved the `storePickupProductTitle` value to a child object, breaking InventoryWatch parsing. this value wasn't used by the app, though, so the fix was just to remove it as a parsing step. 

also bumps the version to v0.0.9, and does a bit of model code reorganization.

### CODE REVIEW

File: InventoryWatch/Model/Model.swift [hunk 1]
```diff
@@ -461,15 +357,14 @@ final class Model: ObservableObject {
             guard let partsAvailability = storeJSON["partsAvailability"] as? [String: [String: Any]] else { return nil }
             let parsedParts: [PartAvailability] = partsAvailability.values.compactMap { part in
                 guard let partNumber = part["partNumber"] as? String else { return nil }
-                guard let storePickupProductTitle = part["storePickupProductTitle"] as? String else { return nil }
```
Comment (worthbak) [inline InventoryWatch/Model/Model.swift:464]: this is the primary change in this PR, in addition to removing `storePickupProductTitle` from the `PartAvailability` struct.
